# Generated by Django 4.2 on 2024-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='subcategory',
            field=models.ManyToManyField(to='website.subcategory'),
        ),
    ]
